# Generated by Django 3.2 on 2021-04-20 03:40

from django.db import migrations, models
import hrm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateTimeField()),
                ('password', models.CharField(max_length=250)),
                ('avatar', models.ImageField(blank=True, upload_to=hrm.models.User.upload_avatar)),
            ],
        ),
    ]
