# Generated by Django 3.2 on 2021-04-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_dept_document_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='manager',
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.document'),
        ),
        migrations.AddField(
            model_name='user',
            name='works_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.dept'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='handles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.document'),
        ),
    ]
