# Generated by Django 3.2 on 2021-04-21 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20210420_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='user',
            name='has_uploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
