# Generated by Django 3.2 on 2021-04-21 08:08

from django.db import migrations, models
import hrm.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_auto_20210421_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=hrm.models.Document.upload_document),
        ),
    ]
