# Generated by Django 3.2 on 2021-04-21 09:47

from django.db import migrations, models
import hrm.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=hrm.models.User.upload_avatar),
        ),
    ]
